"""premium seller column

Revision ID: b37eb48bba5c
Revises: e51e0ff2b761
Create Date: 2023-06-30 15:26:22.916935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37eb48bba5c'
down_revision = 'e51e0ff2b761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usernew', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usernew', schema=None) as batch_op:
        batch_op.drop_column('premium')

    # ### end Alembic commands ###
